### ISSUE TITLE
fix AttributeError: 'Ship' object has no attribute 'blitme'

### ISSUE THREAD

**Issue by wldasf** [wldasf/alien_invasion#1]
pygame 2.5.2 (SDL 2.28.2, Python 3.10.12)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/home/waleed/fun/projects/alien_invasion/alien_invasion.py", line 43, in <module>
    ai.run_game()
  File "/home/waleed/fun/projects/alien_invasion/alien_invasion.py", line 36, in run_game
    self.ship.blitme()
AttributeError: 'Ship' object has no attribute 'blitme'

**Comment by wldasf** [comment]
Fixed: blitme method in the ship module wasn't aligned in the class.
